plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-jsdoc'
  - 'prettier-plugin-packagejson'
  - 'prettier-plugin-sort-json'
  - 'prettier-plugin-css-order'
  - 'prettier-plugin-organize-attributes'
  - 'prettier-plugin-vitepress'

printWidth: 80
semi: false
singleQuote: true
trailingComma: 'none'

importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder:
  - '^vitepress$'
  - '^vitepress([-/].*)?$'
  - '^vue$'
  - '^vite$'
  - '^@[a-zA-Z0-9-]+/(.*)$'
  - '^@/(.*)$'
  - '^[./]'
  - '^(.*)$'

overrides:
  - files: ['*.json']
    options:
      jsonRecursiveSort: true

  - files: ['*.vue']
    options:
      printWidth: 120
      attributeGroups:
        - '^((v-bind)?:?|v-)is$'
        - '^v-for$'
        - '^v-(if|else-if|else|show|cloak)$'
        - '^v-(once|pre|memo)$'
        - '^(v-bind)?:?id$'
        - '^(v-bind)?:?key$'
        - '^(v-bind)?:?ref$'
        - '^(v-)?slot$'
        - '^#'
        - '^v-model$'
        - '^v-(?!bind(:|$)|on(:|$)|html$|text$)'
        - '^class$'
        - '^(v-bind)?:class$'
        - '^((v-bind)?:)?(?!data-|v-|:|@|#)'
        - '$DEFAULT'
        - '^((v-bind)?:)?data-'
        - '^v-bind$'
        - '^v-on:'
        - '^@'
        - '^v-html$'
        - '^v-text$'
