packages:
  - src
  - docs

catalog:
  vitepress: 2.0.0-alpha.17
  vue: ^3.5.34

allowBuilds:
  esbuild: true
  simple-git-hooks: true

shellEmulator: true
autoInstallPeers: false
minimumReleaseAge: 0
