declare module '@theojs/lumen/style' {}
declare module '@theojs/lumen/icon' {}
declare module '@theojs/lumen/button' {}
declare module '@theojs/lumen/colors' {}
declare module '@theojs/lumen/doc' {}
declare module '@theojs/lumen/doc-blocks' {}
declare module '@theojs/lumen/home' {}
declare module '@theojs/lumen/pic' {}
declare module '@theojs/lumen/badge' {}
declare module '@theojs/lumen/components-var' {}
