name: commitlint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          run_install: true
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Print versions
        run: |
          git --version
          node --version
          pnpm --version
          pnpm dlx commitlint --version

      - name: Install commitlint
        run: pnpm add -D conventional-changelog-conventionalcommits commitlint

      - name: Validate current commit (last commit)
        if: github.event_name == 'push'
        run: pnpm dlx commitlint --last --verbose

      - name: Validate PR commits
        if: github.event_name == 'pull_request'
        run: pnpm dlx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
